// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSwitchBotCredentials() {
  return window['go']['main']['App']['ClearSwitchBotCredentials']();
}

export function GetSwitchBotCredentialStatus() {
  return window['go']['main']['App']['GetSwitchBotCredentialStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function SaveSwitchBotCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveSwitchBotCredentials'](arg1, arg2);
}
