// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSwitchBotCredentials():Promise<void>;

export function GetSwitchBotCredentialStatus():Promise<main.CredentialStatus>;

export function Greet(arg1:string):Promise<string>;

export function OpenConfigFolder():Promise<void>;

export function SaveSwitchBotCredentials(arg1:string,arg2:string):Promise<void>;
